### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by marikonemoto** [marikonemoto/furima-32540#9]
# URL
https://furima-32540.herokuapp.com/

# Basic認証のIDとパスワード
ID: nemotoma
Password: 0706

# 出品者用のメールアドレスとパスワード
Email: mail@mail
Password: 123456a

# 購入者用のメールアドレスとパスワード
Email: m@m
Password: 123456a

# 購入用カードの番号・期限・セキュリティコード
Card number: 4242424242424242
期限: Exp-month: 3, Exp-year: 23
CVC(セキュリティコード): 123

**Comment by rumaruma0408** [comment]
marikonemotoさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
